Revert "fix(snap): Fix get-architectures workflow errors due to unsupported build-on snapcraft property syntax(take 2)"
The get-architectures failed with the following error message:

```
 Error: csv encoding only works for arrays of scalars (string/numbers/booleans), child[0] is a !!seq
```

This reverts commit 550a550057ce9fa8555bdae75608dc2b831a7407.